# Generated by Django 5.0.7 on 2024-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="items")),
                ("name", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=255)),
            ],
        ),
    ]
