# Generated by Django 5.0.7 on 2024-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="year",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
