# Generated by Django 5.0.3 on 2024-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_cards_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="detailed_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
