# Generated by Django 5.0.3 on 2024-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_cards_detailed_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="lang",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
