# Generated by Django 5.0.3 on 2024-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_cards_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cards",
            name="img",
            field=models.ImageField(upload_to="images"),
        ),
    ]
