# Generated by Django 5.0.3 on 2024-07-21 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_imdb"),
    ]

    operations = [
        migrations.DeleteModel(
            name="imdb",
        ),
    ]
