# Generated by Django 5.0.3 on 2024-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_imdb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cards",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="imdb",
            name="lang",
        ),
        migrations.AlterField(
            model_name="cards",
            name="desc",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="imdb",
            name="desc",
            field=models.TextField(max_length=1000),
        ),
    ]
