# Generated by Django 5.0.3 on 2024-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_delete_imdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="imdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images")),
                ("name", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=15)),
                ("duration", models.CharField(max_length=15)),
                ("detailed_description", models.TextField(blank=True, max_length=1000)),
                ("lang", models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
